import "./globals.css";
import Header from '../components/Header/Header'
import style from "../styles/reset.scss";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#000325",
  appleMobileWebAppStatusBarStyle: "black-translucent",

};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
