import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/header";
import style from "../styles/reset.scss";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
